/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as BallotRouteImport } from './routes/ballot'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResultsElectionIdRouteImport } from './routes/results.$electionId'
import { Route as AdminVotersRouteImport } from './routes/admin.voters'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOfficialsRouteImport } from './routes/admin.officials'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminElectionsIndexRouteImport } from './routes/admin.elections.index'
import { Route as AdminElectionsNewRouteImport } from './routes/admin.elections.new'
import { Route as AdminElectionsElectionIdIndexRouteImport } from './routes/admin.elections.$electionId.index'
import { Route as AdminElectionsElectionIdTallyRouteImport } from './routes/admin.elections.$electionId.tally'
import { Route as AdminElectionsElectionIdReportRouteImport } from './routes/admin.elections.$electionId.report'

const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const BallotRoute = BallotRouteImport.update({
  id: '/ballot',
  path: '/ballot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResultsElectionIdRoute = ResultsElectionIdRouteImport.update({
  id: '/results/$electionId',
  path: '/results/$electionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVotersRoute = AdminVotersRouteImport.update({
  id: '/voters',
  path: '/voters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfficialsRoute = AdminOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionsIndexRoute = AdminElectionsIndexRouteImport.update({
  id: '/elections/',
  path: '/elections/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionsNewRoute = AdminElectionsNewRouteImport.update({
  id: '/elections/new',
  path: '/elections/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminElectionsElectionIdIndexRoute =
  AdminElectionsElectionIdIndexRouteImport.update({
    id: '/elections/$electionId/',
    path: '/elections/$electionId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminElectionsElectionIdTallyRoute =
  AdminElectionsElectionIdTallyRouteImport.update({
    id: '/elections/$electionId/tally',
    path: '/elections/$electionId/tally',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminElectionsElectionIdReportRoute =
  AdminElectionsElectionIdReportRouteImport.update({
    id: '/elections/$electionId/report',
    path: '/elections/$electionId/report',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/ballot': typeof BallotRoute
  '/confirm': typeof ConfirmRoute
  '/receipt': typeof ReceiptRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/voters': typeof AdminVotersRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/elections/new': typeof AdminElectionsNewRoute
  '/admin/elections/': typeof AdminElectionsIndexRoute
  '/admin/elections/$electionId/report': typeof AdminElectionsElectionIdReportRoute
  '/admin/elections/$electionId/tally': typeof AdminElectionsElectionIdTallyRoute
  '/admin/elections/$electionId/': typeof AdminElectionsElectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/ballot': typeof BallotRoute
  '/confirm': typeof ConfirmRoute
  '/receipt': typeof ReceiptRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/voters': typeof AdminVotersRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/elections/new': typeof AdminElectionsNewRoute
  '/admin/elections': typeof AdminElectionsIndexRoute
  '/admin/elections/$electionId/report': typeof AdminElectionsElectionIdReportRoute
  '/admin/elections/$electionId/tally': typeof AdminElectionsElectionIdTallyRoute
  '/admin/elections/$electionId': typeof AdminElectionsElectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/ballot': typeof BallotRoute
  '/confirm': typeof ConfirmRoute
  '/receipt': typeof ReceiptRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/officials': typeof AdminOfficialsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/voters': typeof AdminVotersRoute
  '/results/$electionId': typeof ResultsElectionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/elections/new': typeof AdminElectionsNewRoute
  '/admin/elections/': typeof AdminElectionsIndexRoute
  '/admin/elections/$electionId/report': typeof AdminElectionsElectionIdReportRoute
  '/admin/elections/$electionId/tally': typeof AdminElectionsElectionIdTallyRoute
  '/admin/elections/$electionId/': typeof AdminElectionsElectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ballot'
    | '/confirm'
    | '/receipt'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/candidates'
    | '/admin/officials'
    | '/admin/settings'
    | '/admin/voters'
    | '/results/$electionId'
    | '/admin/'
    | '/admin/elections/new'
    | '/admin/elections/'
    | '/admin/elections/$electionId/report'
    | '/admin/elections/$electionId/tally'
    | '/admin/elections/$electionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/ballot'
    | '/confirm'
    | '/receipt'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/candidates'
    | '/admin/officials'
    | '/admin/settings'
    | '/admin/voters'
    | '/results/$electionId'
    | '/admin'
    | '/admin/elections/new'
    | '/admin/elections'
    | '/admin/elections/$electionId/report'
    | '/admin/elections/$electionId/tally'
    | '/admin/elections/$electionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ballot'
    | '/confirm'
    | '/receipt'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/candidates'
    | '/admin/officials'
    | '/admin/settings'
    | '/admin/voters'
    | '/results/$electionId'
    | '/admin/'
    | '/admin/elections/new'
    | '/admin/elections/'
    | '/admin/elections/$electionId/report'
    | '/admin/elections/$electionId/tally'
    | '/admin/elections/$electionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BallotRoute: typeof BallotRoute
  ConfirmRoute: typeof ConfirmRoute
  ReceiptRoute: typeof ReceiptRoute
  ResultsElectionIdRoute: typeof ResultsElectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ballot': {
      id: '/ballot'
      path: '/ballot'
      fullPath: '/ballot'
      preLoaderRoute: typeof BallotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/results/$electionId': {
      id: '/results/$electionId'
      path: '/results/$electionId'
      fullPath: '/results/$electionId'
      preLoaderRoute: typeof ResultsElectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voters': {
      id: '/admin/voters'
      path: '/voters'
      fullPath: '/admin/voters'
      preLoaderRoute: typeof AdminVotersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/officials': {
      id: '/admin/officials'
      path: '/officials'
      fullPath: '/admin/officials'
      preLoaderRoute: typeof AdminOfficialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/': {
      id: '/admin/elections/'
      path: '/elections'
      fullPath: '/admin/elections/'
      preLoaderRoute: typeof AdminElectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/new': {
      id: '/admin/elections/new'
      path: '/elections/new'
      fullPath: '/admin/elections/new'
      preLoaderRoute: typeof AdminElectionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/$electionId/': {
      id: '/admin/elections/$electionId/'
      path: '/elections/$electionId'
      fullPath: '/admin/elections/$electionId/'
      preLoaderRoute: typeof AdminElectionsElectionIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/$electionId/tally': {
      id: '/admin/elections/$electionId/tally'
      path: '/elections/$electionId/tally'
      fullPath: '/admin/elections/$electionId/tally'
      preLoaderRoute: typeof AdminElectionsElectionIdTallyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/elections/$electionId/report': {
      id: '/admin/elections/$electionId/report'
      path: '/elections/$electionId/report'
      fullPath: '/admin/elections/$electionId/report'
      preLoaderRoute: typeof AdminElectionsElectionIdReportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminOfficialsRoute: typeof AdminOfficialsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVotersRoute: typeof AdminVotersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminElectionsNewRoute: typeof AdminElectionsNewRoute
  AdminElectionsIndexRoute: typeof AdminElectionsIndexRoute
  AdminElectionsElectionIdReportRoute: typeof AdminElectionsElectionIdReportRoute
  AdminElectionsElectionIdTallyRoute: typeof AdminElectionsElectionIdTallyRoute
  AdminElectionsElectionIdIndexRoute: typeof AdminElectionsElectionIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminOfficialsRoute: AdminOfficialsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVotersRoute: AdminVotersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminElectionsNewRoute: AdminElectionsNewRoute,
  AdminElectionsIndexRoute: AdminElectionsIndexRoute,
  AdminElectionsElectionIdReportRoute: AdminElectionsElectionIdReportRoute,
  AdminElectionsElectionIdTallyRoute: AdminElectionsElectionIdTallyRoute,
  AdminElectionsElectionIdIndexRoute: AdminElectionsElectionIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BallotRoute: BallotRoute,
  ConfirmRoute: ConfirmRoute,
  ReceiptRoute: ReceiptRoute,
  ResultsElectionIdRoute: ResultsElectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
